### PR TITLE
Mccalluc/tutorial tests

### PR DESCRIPTION
**Pull request by mccalluc**
@thinkh: Do you have thoughts on this? The idea would be to have a test-#.js in parallel with each code-#.js, and use qunit to run the tests. It works in my browser, but not in phantomjs for me right now. Trying selenium would be one option, or maybe look closer at the phantomjs code I just copied and pasted.

### CODE REVIEW

**Comment by mccalluc** [comment]
@thinkh : I'm not making much progress here and am going to take a break from it. The tests pass [locally](http://localhost:5000/_documentation/tutorial/web_bundle/qunit.html?0), but when run on travis it fails [here](https://travis-ci.org/Caleydo/caleydo.github.io/builds/158817000#L270)... It seems that `Caleydo.d3.parser` is defined, but empty? Knowing what you know about the system, can you imagine something partially loading that would explain this?

There are other directions I could push this:
- drop phantomjs and use selenium: This is adding another layer of complexity, so not my preference.
- Try taking qunit out of the equation, but I think it's comparatively simple and not likely to be the root of the problems.
- Try running phantomjs a different way. Lots of tutorials on the web use grunt instead of running it directly, but I don't think that's going to fix anything.
- Maybe there's a difference in the versions of phantomjs between what I have and what runs on travis? I could check this now...
- slimerjs + xvfb? phantomjs is built in with travis, so it'd be sad if we needed to install something extra.

**Comment by mccalluc** [comment]
Travis is running 1.9.8; Locally I have 2.1.1: https://github.com/travis-ci/travis-ci/issues/3225
... but even if that worked, I'd still be having the problems I have locally with `Promise`... Maybe there's a polyfill for that?

**Comment by mccalluc** [comment]
argh. Was hoping that travis and local would at least fail the same way with the last commit. But no luck.

**Comment by mccalluc** [comment]
Replaced by #115. PhantomJS is just not going to work because it trails too far behind the browsers we're targeting. With Selenium, the webdriver version doesn't matter: we can use any version of FF behind the scenes.

**Comment by mstreit** [comment]
Seems that you had a very productive weekend. Thanks!

Could we also run the tests for multiple browsers (Chrome, FF, Opera)?

**Comment by mccalluc** [comment]
@mstreit: maybe? FF has the best support, and while there are drivers for the others, it'll take some work. The other half of the problem is getting the other browsers installed on Travis. I've just filed #116 for this.

(Another axis is version support... I just grabbed the version number of my local browser... This is neither the oldest version the code could run on, nor the most recent release.)

**Comment by mstreit** [comment]
Moving conversation about browsers to #116.

**Pull request closed without merging**
